apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: pihole
data:
  TZ: "Europe/Amsterdam"
  DNS1: "127.0.0.1#5054"
  DNS2: "127.0.0.1#5054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap-cloudflared
  namespace: pihole
data:
  MAX_UPSTREAM_CONNS: "50"