#usage get-content .\deployment.yaml | %{$_ -replace "#NODE#","a"} | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole-#NODE#
  name: pihole-#NODE#
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-#NODE#
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole-#NODE#
    spec:
      hostAliases:
      - ip: "192.168.0.50"
        hostnames:
        - "pihole.ronneylira.com"
        - "pihole2.ronneylira.com"
      containers:
      - envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
        image: pihole/pihole:latest
        imagePullPolicy: Always
        name: pihole
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dchp
          containerPort: 67
          protocol: UDP
        - name: web
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        resources:
          requests:
            cpu: "40m"
            memory: "70Mi"
          limits:
            cpu: "200m"
            memory: "150Mi"
        livenessProbe:
            httpGet:
                path: /admin.index.php
                port: web
            initialDelaySeconds: 60
            failureThreshold: 10
            timeoutSeconds: 5
        readinessProbe:
            httpGet:
                path: /admin.index.php
                port: web
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
        volumeMounts:
          - name: pihole-etc-volume-#NODE#
            mountPath: /etc/pihole/
          - name: pihole-dnsmasqd-volume-#NODE#
            mountPath: /etc/dnsmasq.d/
      - envFrom:
        - configMapRef:
            name: env-configmap-cloudflared
        name: cloudflared
        image: visibilityspots/cloudflared:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5054
          protocol: TCP
        - containerPort: 5054
          protocol: UDP
        resources:
          requests:
            cpu: "30m"
            memory: "40Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
        readinessProbe:
          exec:
            command: ['dig', '-p', '5054', '@127.0.0.1', 'pi-hole.net']
          timeoutSeconds: 10
          initialDelaySeconds: 5
          periodSeconds: 10 
        livenessProbe:
          exec:
            command: ['dig', '-p', '5054', '@127.0.0.1', 'google.com']
          timeoutSeconds: 10
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 2
      restartPolicy: Always
      volumes:
      - name: pihole-etc-volume-#NODE#
        persistentVolumeClaim:
          claimName: pihole-etc-volume-#NODE#
      - name: pihole-dnsmasqd-volume-#NODE#
        persistentVolumeClaim:
          claimName: pihole-dnsmasqd-volume-#NODE#