apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pihole
  namespace: pihole
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pihole
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70