#usage get-content .\deployment.yaml | %{$_ -replace "#NODE#","a"} | kubectl apply -f -
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-web-#NODE#
  namespace: pihole
  labels:
    app: pihole-#NODE#
spec:
  selector:
    app: pihole-#NODE#
  ports:
  - protocol: TCP
    port: 80
    name: web
    targetPort: 80
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-tcp-#NODE#
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pihole-#NODE#
  ports:
  - protocol: TCP
    port: 53
    name: dnstcp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.0.12
  externalTrafficPolicy: Local
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-udp-#NODE#
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pihole-#NODE#
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.0.12
  externalTrafficPolicy: Local
---