---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-volume
  namespace: pihole
spec:
  storageClassName: nfs-csi-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasqd-volume
  namespace: pihole
spec:
  storageClassName: nfs-csi-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi