apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-volume-#NODE#
  namespace: pihole
spec:
  storageClassName: nfs-csi-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasqd-volume-#NODE#
  namespace: pihole
spec:
  storageClassName: nfs-csi-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---